### ISSUE TITLE
Make the site responsive for all screen sizes

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/medi-Care#1]
Make the project responsive for all screen sizes and make sure that in mobile the navbar content must be clearly visible

**Comment by KhushiTayal** [comment]
@mohit200008 I want to work on this issue. Please assign it to me.

**Comment by mohit200008** [comment]
Yes you can @KhushiTayal

**Comment by mohit200008** [comment]
The work will be in bootstrap so work according to that

**Comment by 777ahesh** [comment]
@mohit200008  can i work on this issue

**Comment by mohit200008** [comment]
Yes go ahead @777ahesh

**Comment by sagnik2001** [comment]
Can I work on this under GSSoC 22

**Comment by sulogna2001** [comment]
Hey Can you assign me this issue for GSsoc22
