### ISSUE TITLE
Cardiovascular Disease Prediction Notebook

### ISSUE THREAD

**Issue by Garvit414** [mohit200008/medi-Care#110]
### Is your feature request related to a problem? Please describe.

We can add a model which can predicts whether a person is suffering from cardiovascular disease or not.

### Describe the solution you'd like.

It will add one more feature in web application which predicts whether a person is suffering from cardiovascular disease or not.

**Comment by Garvit414** [comment]
@mohit200008 I want to make notebook of Cardiovascular Disease Prediction. Please assign it to me under KWoC.

**Comment by mohit200008** [comment]
yes @Garvit414  go ahead
