### ISSUE TITLE
Covid-19 update and chat box issue

### ISSUE THREAD

**Issue by PranayKumar1801** [mohit200008/medi-Care#112]
### Is your feature request related to a problem? Please describe.

- After opening the page , there should be a alert link below the navigation bar which will give the  update of Covid-19 to peoples.
- Secondary,  the chat box it is not getting closed after clicking cross button.

### Describe the solution you'd like.

- The alert  link will redirect to a new page and there it will show the Total active cases ,total people recovered from covid-19 and the total cases found in India.
The all data will be shown in number as well as in graph (for different states).

- The Chat box should be closed when clicked on close button and  I want to fix that issue.

**Comment by PranayKumar1801** [comment]
@mohit200008  Can I close this issue?? As it is  completed and merged successfully.

**Comment by mohit200008** [comment]
Yes

**Comment by PranayKumar1801** [comment]
#112 covid 19 update
