### ISSUE TITLE
a and href is used instead of link to of react router dom

### ISSUE THREAD

**Issue by shobhit10058** [mohit200008/medi-Care#12]
In Doctor component, a and href are used to load details. Link to can be used to render details without re-loading the page.

**Comment by shobhit10058** [comment]
I have fixed it but map is giving issues but the navigation can be done using Link to.

**Comment by mohit200008** [comment]
Can you fix the map issue ??

**Comment by shobhit10058** [comment]
I don't know about it but I will try.

**Comment by mohit200008** [comment]
Are you contributing under KWOC ??

**Comment by shobhit10058** [comment]
yes

**Comment by mohit200008** [comment]
have you joined the discord channel ?

**Comment by shobhit10058** [comment]
yes
