### ISSUE TITLE
[The BMI calculator is accepting negative values.] 

### ISSUE THREAD

**Issue by Ayusht777** [mohit200008/medi-Care#140]
### What happened?

The BMI calculator is currently allowing the input of negative values, which is unintended behavior. It should be modified to handle only positive values as negative values are not applicable in the context of BMI calculations

### How can we reproduce this bug?

Entering a negative value into it.

### Urgency (Optional)

Medium priority

**Comment by mohit200008** [comment]
you can work on it @Ayusht777

**Comment by Ayusht777** [comment]
YES

**Comment by mohit200008** [comment]
Did you install the dependencies using npm install
