### ISSUE TITLE
Create a form for adding a doctor.

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/medi-Care#26]
Create a form on the Health page for adding a doctor. It should have doctor's name , age , Years of experience , review for this doctor , Area of specialization, Phone number and Address of the doctor. Only frontend has to be made.

**Comment by kunal-umap** [comment]
I want to work on this Issue , Would you please assign me ??

**Comment by mohit200008** [comment]
go ahead @kunal-umap

**Comment by kunal-umap** [comment]
yes !

**Comment by kunal-umap** [comment]
Would all field need to be mandatary ??

**Comment by mohit200008** [comment]
Not all fields, but the name ,the rating , and area of specialization

**Comment by mohit200008** [comment]
The sequence can be anything no restrictions on that. But the name ,age, area of specialization should be first and then the rest.

**Comment by kunal-umap** [comment]
![image](https://user-images.githubusercontent.com/80446986/145810121-fb4c6496-0205-400c-9967-78aca62f7704.png)


 Is it ok , should I create pull request ?

**Comment by mohit200008** [comment]
->The area of specialization will be dropdown having the various options 
-> And the form is quite big , leave some space from all sides
->Can you make this form appear as when someone clicks on add doctor on the health page , this form comes up and the rest content behind it is blurred and this form appears with a transition ease in and out.
->Also the input bars are big which takes away the  simpleness of the form .

**Comment by mohit200008** [comment]
Work On these points and if you have any doubts you can connect with me anytime

**Comment by kunal-umap** [comment]
https://user-images.githubusercontent.com/80446986/146215386-2b62c00c-7dba-491f-a182-e40c525f9c62.mp4

What changes should I make now In this ??
And What are the Drop Down

**Comment by mohit200008** [comment]
Dropdown down options you can enter 4 to 5 options , areas of specializations and this button has to be on the health page where doctors are present . also there can be some transition when the form opens it will look good.And the area of specialization is appearing 2 times. It just has be  a dropdown.

**Comment by kunal-umap** [comment]
https://user-images.githubusercontent.com/80446986/146636411-c254b2ee-193f-49de-a633-821f91a5888b.mp4

Now is it Ok ?

**Comment by mohit200008** [comment]
yes
