### ISSUE TITLE
Redesign the navbar 

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/medi-Care#28]
The navbar should be redesigned according to the color scheme of the page and it should  be visible even after the user scrolls down.

**Comment by suyogkokaje** [comment]
Hello @mohit200008 I would like to work on this issue. Could you please assign this issue to me?

**Comment by mohit200008** [comment]
sure @suyogkokaje  go ahead

**Comment by suyogkokaje** [comment]
I am unable to resolve this issue. Sorry for inconvenience 😔.

**Comment by aniketpathak028** [comment]
Hey @mohit200008, I feel I can resolve this issue, can you assign this to me?

**Comment by mohit200008** [comment]
sure @aniketpathak028  go ahead
