### ISSUE TITLE
News on Disease Prediction page

### ISSUE THREAD

**Issue by kapoor-hub** [mohit200008/medi-Care#31]
Just imagine when user open disease prediction page he/she can see some news how many people died and suffers alot because of some disease they don't even know about and they can cure it if they know about that disease at early stage. Because of this people will take the problem and advise a little bit serious. These news pop up will come on the left side of the disease prediction page where . I will also try to make it responsive. Can you assign this to me.@mohit200008

**Comment by mohit200008** [comment]
On the disease prediction page, news can be displayed And the cards for the disease prediction can be below the news portion in a horizontal direction with an improved CSS. 
Above the cards the news can be displayed covering the whole page. 
You can implement it @kapoor-hub

**Comment by kapoor-hub** [comment]
[image: proto.png]
sir i have imagined this type of page layout on the upper side news will be
shown under that disease prediction option will appear. Are u comfortable
with that ignore the black color.

**Comment by mohit200008** [comment]
image is not visible can you connect on discord

**Comment by kapoor-hub** [comment]
i tried it previously but it shows invite is expired.

**Comment by mohit200008** [comment]
https://discord.gg/YDFUs5E9

**Comment by mohit200008** [comment]
You can connect on this

**Comment by kapoor-hub** [comment]
sir currently my internal tests are going on i will give you all updates
tomorrow. is it ok.

**Comment by mohit200008** [comment]
yes

**Comment by mohit200008** [comment]
@kapoor-hub  when you're done share the photo here or on discord

**Comment by kapoor-hub** [comment]
sry i m unable to do this sry for inconvenience.

**Comment by Ashsenior** [comment]
Hey , mohit I have some previous experience using spotify api in my webapp  .I have searched for some newsapi and can integrate that into the webapp .
I'm a participant of GSSoC'22 .
Want me to work on it ??

**Comment by Ashsenior** [comment]
And I saw that u were migrating the backend to django I can work on that also .

**Comment by mohit200008** [comment]
You can work on it and after completion you can send a demo before making a pr

**Comment by Ashsenior** [comment]
do you want me to work on changing the backend or the news api ??

**Comment by mohit200008** [comment]
First change the backend

**Comment by Ashsenior** [comment]
I will change the backend but it will require some time around 10-15 days because I have to recreate the app and I will convert all the html files into react components .

**Comment by mohit200008** [comment]
Sure go ahead but make sure everything works fine after your work is done

**Comment by Ashsenior** [comment]
Hey , so I have completed the frontend and little bit backend part for shifting but I see that there are only prediction files in here one for heart and other for kidney ??

**Comment by Ashsenior** [comment]
i have shifted the backend and everything seems to be working fine should i create a new issue for the shifting backend and make a PR for that ??

**Comment by mohit200008** [comment]
okay make a pr the mentors will check  the code, also provide  a code to confirm that things are working as expected

**Comment by Ashsenior** [comment]
hey , @mohit200008 I am now working on this issue . Can you please reconsider it as a level3 issue .
