### ISSUE TITLE
Hindi page similar to English home page

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/medi-Care#33]
The Hindi language page should be similar to the English page,  Including all the photos(can be different) in carousel , The CSS and everything just the language should be changed to Hindi

**Comment by qadirpervez** [comment]
Hello @mohit200008 can you please explain a little more, I would like to do it

![image](https://user-images.githubusercontent.com/14182769/145892186-ba4e4b50-7e75-4870-9283-ae5b7a1306b6.png)

the site is already multilingual. Do you want the navigation to be changed?

**Comment by mohit200008** [comment]
Change the photos and CSS similar to the English home page 
You can use photos related to medical  or the same photos but it should be relevant

**Comment by mohit200008** [comment]
And yes it would be better if the navigation on the hindi page is in hindi too

**Comment by mohit200008** [comment]
You can work on it @qadirpervez
