### ISSUE TITLE
Add a carousel on the home page with the pictures related to medical

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/medi-Care#4]

**Comment by artimanputra** [comment]
I would like to work on this issue, Can you assign it to me?

**Comment by mohit200008** [comment]
@artimanputra  yes go ahead

**Comment by suyogkokaje** [comment]
Hello @mohit200008 I would like to work on this issue. Could you please assign this issue to me?

**Comment by mohit200008** [comment]
@artimanputra  is working on this one, You can look for another issue for now.
