### ISSUE TITLE
Change the react icon on the top to a medical related icon

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/medi-Care#5]

**Comment by SachinMittal1766** [comment]
I would like to work on this. Pls assign it to me @mohit200008

**Comment by mohit200008** [comment]
Sure @SachinMittal1766  go ahead

**Comment by SachinMittal1766** [comment]
Icon Design @mohit200008 
![Medi-Care Logo](https://user-images.githubusercontent.com/82721772/144836695-8ecf56a1-dd49-4df3-b852-178a4bd71cd8.png)

**Comment by mohit200008** [comment]
Can you apply and send a sc just to see how it looks

**Comment by SachinMittal1766** [comment]
I searched in every folder but didn't get the favicon folder. Would you @mohit200008 please tell me where it is?

**Comment by mohit200008** [comment]
Public folder / index.html

**Comment by SachinMittal1766** [comment]
![Screenshot (709)](https://user-images.githubusercontent.com/82721772/144973590-0874c621-0c8d-4e00-8ff6-629f29815ecd.png)
This is the look of icon after applying.

**Comment by mohit200008** [comment]
Can you show some other examples too ???

**Comment by mohit200008** [comment]
And can you apply some border-radius on this one, The corners can be a little curved

**Comment by SachinMittal1766** [comment]
![Medi CAre](https://user-images.githubusercontent.com/82721772/145152195-ad4e84a7-2623-4192-b33c-872426e3ffde.png)
![Medi CAre (1)](https://user-images.githubusercontent.com/82721772/145152537-0f04bc01-32ab-4d3e-ba2d-9df175b96153.png)
Some more designs

**Comment by mohit200008** [comment]
apply the red one
