### ISSUE TITLE
add the rubber band effect on the buttons 

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/medi-Care#55]
https://codepen.io/chronisp/pen/WqGxdW
see this page, to get an idea

**Comment by Anirban-1490** [comment]
@mohit200008 have to do this effect for all buttons ? and assign it to me

**Comment by mohit200008** [comment]
Yes and also add transition while navigating from one page to another

**Comment by mohit200008** [comment]
> > Yes and also add transition while navigating from one page to another
> 
> you mean loading spinner ?

like when you navigate there's an ease in out transition and the loading spinner can be applied when user clicks on predict button

**Comment by Anirban-1490** [comment]
> > > Yes and also add transition while navigating from one page to another
> > 
> > 
> > you mean loading spinner ?
> 
> like when you navigate there's an ease in out transition and the loading spinner can be applied when user clicks on predict button

ok assign it to me under gssoc22

**Comment by Aditya3403** [comment]
Sir I would like to work on this issue. kindly assign this issue to me.

**Comment by mohit200008** [comment]
yes go ahead @Anirban-1490
