### ISSUE TITLE
Add multiclass Brain tumor classification and Alzheimer detection using MRI image

### ISSUE THREAD

**Issue by gautamgc17** [mohit200008/medi-Care#57]
Hey I wanted to add Brain tumor classification and Alzheimer classification model using MR images. Both the projects have a four-way classification.
-  Brain Tumors are classified as: Benign Tumor, Malignant Tumor, Pituitary Tumor and No tumor.
- The Alzheimer stage is classified into following: Mild Demented, Moderate Demented, Non Demented, Very Mild Demented

Additionally, we can show the GradCAM visualization along with the prediction to obtain a class activation heatmap for these classification models.

**Comment by mohit200008** [comment]
Yes you can work on theses tasks. But make sure the backend has to be in django not flask.
