### ISSUE TITLE
Shifting backend from Flask to Django 

### ISSUE THREAD

**Issue by Ashsenior** [mohit200008/medi-Care#63]
I have shifted the backend and converted all html files into react components assign me this issue @mohit200008 so that I can make a PR for this .

**Comment by mohit200008** [comment]
make a pr for this and the project mentors will be reviewing your code

**Comment by mohit200008** [comment]
Please make the pr if the work is done @Ashsenior

**Comment by Ashsenior** [comment]
Actually I'm trying to push the project but because I made that project on completely different folder and I have to upload the full project it gitbash is showing some error **rpc failed err 8**

**Comment by Ashsenior** [comment]
I have seen some soln and will see if it will work today evening . 
Sorry for the inconvenience and if u can help with this error it will be very helpful 🙂.

**Comment by mohit200008** [comment]
send a sc on discord the mentors will help

**Comment by 2701gouravgoel** [comment]
@Ashsenior pls reach me for help.

**Comment by Ashsenior** [comment]
hey @mohit200008 I have tested the back
![Screenshot (83)](https://user-images.githubusercontent.com/49332381/160434706-e7f65fae-ae5c-45e3-b4b4-e519e091301b.png)
end and separated it from frontend 
Please share the new repo 
![Screenshot (84)](https://user-images.githubusercontent.com/49332381/160434765-214f6223-6269-4d8e-bf1c-f8a7e035370f.png)

**Comment by mohit200008** [comment]
Just share the files

**Comment by Ashsenior** [comment]
Any update ?? @2701gouravgoel  @mohit200008

**Comment by ishashukla183** [comment]
I would like to work on this issue
