### ISSUE TITLE
Improve home page

### ISSUE THREAD

**Issue by AdnanMuzavor** [mohit200008/medi-Care#69]
Improve home page by adding some good looking border to cards, some hover effects and responsive look on mobile devices

**Comment by mohit200008** [comment]
Yes @AdnanMuzavor  you can work on it

**Comment by mohit200008** [comment]
please can you also improve the disease prediction page too ???

**Comment by AdnanMuzavor** [comment]
Okay, I'll raise an issue for it.

**Comment by Muskan626bidani** [comment]
@mohit200008 Hi, can I work on this issue if this is still open under GSSOC'22

**Comment by mohit200008** [comment]
@Muskan626bidani  this issue has already been resolved. You can look up for other issues
