### ISSUE TITLE
The map is not working as expected 

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/medi-Care#7]
Remove the google api and make use of leaflet to show the map. Or change the google API so its able to show the locations.

**Comment by aksh-hash** [comment]
Sir, I can work on this.

**Comment by mohit200008** [comment]
yes @aksh-hash  go for it

**Comment by aksh-hash** [comment]
Thank you sir , I'll work my level best.

**Comment by mohit200008** [comment]
This issue has been fixed
