### ISSUE TITLE
Optimizing the images

### ISSUE THREAD

**Issue by harsh5902** [mohit200008/medi-Care#70]
While going through code and running it I came across that it takes lot of time to load the website. As there are lot of images in the website there is a high probability that images are not optimized properly which causes slow loading.

Assign me the issue I will solve the slow loading issue by optimizing images, removing excessive CSS(another factor) or any other factor.

**Comment by mohit200008** [comment]
Okay go ahead @harsh5902

**Comment by harsh5902** [comment]
Shall I add my image optimizing code as well? So that in future anyone wants to add the image they can optimize it first and then add it.

**Comment by mohit200008** [comment]
Yes

**Comment by mohit200008** [comment]
But make sure it doesn't give any errors
