### ISSUE TITLE
Language toggle not working properly

### ISSUE THREAD

**Issue by prabhkaur301** [mohit200008/medi-Care#73]
## Issue Type:

- [X] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- Once the language get changed from English to Hindi , it does not toggle back to English on clicking the button. 

I'm GSSOC'22 participant, please assign this issue to me

**Comment by mohit200008** [comment]
Go ahead @prabhkaur301

**Comment by prabhkaur301** [comment]
Solved the issue & PR created #76
