### ISSUE TITLE
Convert class Component into functional Component

### ISSUE THREAD

**Issue by mohit200008** [mohit200008/medi-Care#8]
Convert the class components into functional components where ever-present and make sure that the application works without any errors.

**Comment by shobhit10058** [comment]
I saw that only Doctor component is class based. I have converted it to functional component. Can you assign me this?

**Comment by mohit200008** [comment]
is it working 
can you show a working demo without sound???

**Comment by shobhit10058** [comment]
The google map is constant reloading presently. Other things are working as before. [video_link](https://drive.google.com/file/d/1VX2hKmadTwBgml7aL73ITf7NpZJTmEzi/view?usp=sharing)

**Comment by mohit200008** [comment]
looks good
