### ISSUE TITLE
Redesign the scroll bar and remove the horizontal scroll.

### ISSUE THREAD

**Issue by aktamoli0910** [mohit200008/medi-Care#81]
### Issue

Fix the width of the page so that there is no horizontal scroll and the scroll bar is quite basic. Please redesign the scrollbar to make it a bit attractive.

###  Solution we'd like.

The new designed scroll bar should be #CC5500 in color and add some roundness to the edges as well.

**Comment by vinrusty** [comment]
Can I please work on this issue?

**Comment by mohit200008** [comment]
Sure go ahead @vinrusty
