### ISSUE TITLE
Breast Cancer Prediction

### ISSUE THREAD

**Issue by Shweta2024** [mohit200008/medi-Care#85]
Hello! I'm a GSSoC'22 Contributor. I would like to do EDA followed by using Logistic Regression and Decision Tree for predicting Breast Cancer. Please assign me this task.
Thank you!

**Comment by mohit200008** [comment]
Yes you can work on it @Shweta2024

**Comment by rohitpadage** [comment]
I'm a GSSoC'22 Contributor.
I would like to work on this issue by implementing different ml algorithms for Breast Cancer prediction.

**Comment by mohit200008** [comment]
go ahead @rohitpadage

**Comment by mohit200008** [comment]
Any update @Shweta2024

**Comment by Shweta2024** [comment]
> Any update @Shweta2024
Sir, I have created a PR, please review it.

PR Link :- https://github.com/mohit200008/medi-Care/pull/92
