### ISSUE TITLE
[Bug Title here] Navbar needs to be updated 

### ISSUE THREAD

**Issue by nitishsaini706** [mohit200008/medi-Care#86]
### What happened?

issue #1 
![navbar ](https://user-images.githubusercontent.com/39373956/160834204-a85d2d56-b8a2-4fab-91ec-0806dafd036a.jpg)

### How can we reproduce this bug?

This is related to issue #1 ,also navbar needs some changes in background color 
Scrolling effect background change to transparent 

![navbar issue](https://user-images.githubusercontent.com/39373956/160834984-62163d57-3fc1-402e-8042-c0757bb7cc72.jpg)

**Comment by mohit200008** [comment]
@nitishsaini706  you can work on this issue

**Comment by nitishsaini706** [comment]
@mohit200008 Can you review my pr as i dont think it's level 1 , it's level 2 work i've done .
